# Rename existing files
mv "accessibility.tif" "land availability.tif"
mv "population density.tif" "population density.tif"
mv "air quality.tif" "air quality.tif"
mv "rainfall.tif" "water availability.tif"
mv "biodiversity index.tif" "biodiversity index.tif"
mv "building density.tif" "building density.tif"
mv "building height.tif" "building height.tif"
mv "current road network.tif" "existing road network.tif"
mv "flood risk.tif" "flood risk areas.tif"
mv "habitat connectivity.tif" "existing pollinator populations.tif"
mv "housing density.tif" "zoning regulations.tif"
mv "land availability.tif" "land availability.tif"
mv "pedestrian flow.tif" "pedestrian flow.tif"
mv "soil permeability.tif" "soil permeability.tif"
mv "soil quality.tif" "soil quality.tif"
mv "soil type.tif" "soil type.tif"
mv "sunlight exposure.tif" "solar radiation.tif"
mv "topography.tif" "topography.tif"
mv "urban heat island.tif" "urban heat island.tif"
mv "urban runoff.tif" "impervious surface percentage.tif"
mv "water flow.tif" "watershed boundaries.tif"

# Create new files by duplicating existing ones
cp "land availability.tif" "existing water channels.tif"
cp "air quality.tif" "water pollution levels.tif"
cp "land availability.tif" "agricultural areas.tif"
cp "water availability.tif" "water bodies.tif"
cp "water availability.tif" "water quality.tif"
cp "urban heat island.tif" "green space gaps.tif"
cp "population density.tif" "proximity to residential areas.tif"
cp "pedestrian flow.tif" "public transport stops.tif"
cp "air quality.tif" "noise pollution levels.tif"
cp "water pollution levels.tif" "water pollution sources.tif"
cp "urban heat island.tif" "traffic density.tif"
cp "impervious surface percentage.tif" "parking areas.tif"
cp "land availability.tif" "existing green spaces.tif"
cp "impervious surface percentage.tif" "existing drainage infrastructure.tif"
cp "land availability.tif" "urban agriculture areas.tif"
cp "watershed boundaries.tif" "existing forest cover.tif"
cp "soil quality.tif" "street width.tif"

# Remove any remaining files that are no longer needed
rm "socioeconomic factors.tif"